name: repo_app
description: "A modern, full-featured Telegram Clone built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # مكتبة لإنشاء معرفات فريدة للرسائل والمستخدمين
  uuid: ^4.3.3
  # مكتبة للتعامل مع الوسائط (صور وفيديوهات)
  image_picker: ^1.0.7
  video_player: ^2.8.2
  # مكتبة للتشغيل الصوتي (وهمية في هذه المرحلة)
  # audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
