name: Init and Build Flutter
on:
  workflow_dispatch: # ده هيعملك زرار عشان تشغل البناء بمزاجك

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # إعطاء صلاحية للروبوت يكتب الكود في الريبو

    steps:
      - name: 📥 سحب الريبو
        uses: actions/checkout@v3

      - name: ⚙️ إعداد بيئة Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # أحدث إصدار مستقر

      - name: 🏗️ إنشاء ملفات المشروع ورفعها للريبو
        run: |
          flutter create .
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "🎉 تهيئة مشروع فلاتر الجديد" || echo "لا يوجد جديد للحفظ"
          git push

      - name: 📦 بناء تطبيق الأندرويد (APK)
        run: flutter build apk --release

      - name: 📤 رفع ملف الـ APK للتحميل
        uses: actions/upload-artifact@v3
        with:
          name: Repo_APP_V1
          path: build/app/outputs/flutter-apk/app-release.apk
