name: repo_app
description: "A modern Telegram Clone built with Flutter in 2026."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # مكتبة Ionicons للأيقونات الحديثة اللي تشبه تيليجرام
  ionicons: ^0.2.2
  # مكتبة حديثة جداً لبناء واجهات الشات بسرعة
  flutter_chat_ui: ^1.6.8
  # مكتبات مساعدة لإدارة البيانات والأنيميشن
  flutter_chat_types: ^3.6.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
